version: "3.8"
services:
  backend:
    container_name: backend
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    environment:
      - MONGODB_URI=mongodb://mongo:27017/nodejs
    volumes:
      - "./src:/app/src"
      - /app/node_modules
    networks:
      - trandung
  mongo:
    image: mongo:5.0.5
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    networks:
      - trandung
  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
    expose:
      - "3307"
    ports:
      - "3307:3306"
    networks:
      - trandung
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data/db
    networks:
      - trandung
volumes:
  mongodb:
  redis:
  mysql:
networks:
  trandung:
